apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: image-to-pdf-pvc
  namespace: image-to-pdf

spec:
  storageClassName: ""

  volumeName: image-to-pdf-pv

  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 1Gi